version: 0.0.{build}
image: Visual Studio 2017
configuration: Release
skip_commits:
  message: /.*\[ci\-skip\].*/ 
before_build:
- cmd: dotnet restore src/Vlingo.Common.sln
build:
  project: src/Vlingo.Common.sln
  verbosity: minimal
  publish_nuget: true
test_script:
- cmd: dotnet test src/Vlingo.Common.Tests
deploy:
- provider: NuGet
  api_key:
    secure: u9SMugMjDFnthhyvNTM0cviReNf+kqQUr/hgHHtUl/j6erU1UgFpKuyjtuH3gqwW
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master